<?php

namespace Generator\Command\Admin\Module\Controller;

use Hurah\Types\Type\PlainText;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class AddOverview extends Command {

    protected function configure()
    {
        $this->setName('controller:add:overview');
        $this->setDescription('Create a new overview / collection controller');
        $this->setHelp("Creates an empty controller that renders collections of things.");

        PlainText::

        $this->addArgument('directory', InputOption::VALUE_REQUIRED, 'The directory where the controller should be placed');
    }
    protected function initialize(InputInterface $input, OutputInterface $output)
    {

    }
    protected function interact(InputInterface $input, OutputInterface $output) {
        parent::interact($input, $output); // TODO: Change the autogenerated stub
    }
    protected function execute(InputInterface $input, OutputInterface $output) {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}

